# Generated by Django 3.1.4 on 2021-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='chead3',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead4',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead5',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
